### ISSUE TITLE
Find a format for custom levels which can contain meta data

### ISSUE THREAD

**Issue by signegrau** [MechaGK/LudumDare37#10]
Right now levels are basic text files with symbols presenting tiles. We could either have to files for every level, the one we have now and a meta data file. Or it could all be saved in a XML, JSON or YAML file. I think YAML is wroth a try, which has a library compatible with Unity: https://github.com/aaubry/YamlDotNet

**Comment by signegrau** [comment]
Maybe a level file could look like this?
```yaml
---
id: 123456
name: Cool Level
author: MechaGK
level-data: >
    ###_###_#_#_____#_#_##___#__#_#___#_____###_###_#______________________@______*_####################
...
```
